version: '2.1'
services:
    node:
      image: "node:8"
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      volumes:
        - ./:/home/node/app
      ports:
        - "3090:3090"
      links:
        - mongodb
      command: "npm start"
    mongodb:
      image: mongo:latest
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      healthcheck:
        test: echo 'db.stats().ok' | mongo localhost:27017/auth --quiet
        interval: 5s
        timeout: 5s
        retries: 12
      ports:
        - "27017:27017"
      command: mongod --smallfiles --logpath=/dev/null # --quiet